# Generated by Django 3.0.4 on 2020-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey', '0002_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='choice',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mandatory',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='multiple',
            field=models.BooleanField(),
        ),
    ]
