# Generated by Django 3.0.4 on 2020-06-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey', '0004_auto_20200609_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question',
            new_name='qtn',
        ),
    ]
