# Generated by Django 3.0.4 on 2020-06-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey', '0005_auto_20200609_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='choice',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='qtn',
            field=models.CharField(max_length=100),
        ),
    ]
